# Project Information
site_name: INFO 314 Course Resources
site_description: Documentation and Resources for INFO 314
site_author: Clinton Campbell
site_url: https://info314.tcpip.dev

# Repository
repo_name: quirktree/info314-website
repo_url: https://github.com/quirktree/info314-website
edit_uri: ""

# Site Layout
nav:
  - Home: index.md
  - Projects:
    - 1 - Pi Setup:
      - Raspberry Pi Setup: assignments/pi-setup.md
      - networkd Setup: assignments/networkd-setup.md
      - Wifi Reference: resources/wifi-reference.md
    - 2 - Set up a DHCP Server:
      - IP Address Planning Reference: resources/address-planning.md
      - Installing and Configuring the ISC DHCP Server: assignments/dhcp-setup.md
    - 3 - Configure Routing and NAT:
      - Router Setup: assignments/router-setup.md
      - Introduction to iptables: resources/iptables.md
    - 4 - Configure a DNS Resolver:
      - DNS Resolver Setup: assignments/resolver-setup.md
    - Report - NAT and DNS Analysis:
      - Instructions: assignments/analysis-report.md
      - Installing TShark: resources/tshark-install.md
    - 5 - Configure an Authoritative Name Server:
      - Authoritative Zone Setup: assignments/dns-zone-setup.md
      - DNS Zone Reference: resources/zone-file-format.md
    - Extra Credit:
      - VLAN Challenge: assignments/vlan-challenge.md
    #- Final WAN Project:
    #  - Project Requirements: assignments/final-project.md
  - Labs:
    - Lab 1 - Core Technical Skills: assignments/lab1.md
    - Lab 2 - Analyzing DHCP and ARP with Wireshark: assignments/lab2.md
    - Lab 3 - Analyze Zeroconf in Wireshark: assignments/lab3.md
    - Lab 4 - Analyze DNS & HTTP in Wireshark: assignments/lab4.md
    - Lab 5 - Analyze TCP with ncat and Wireshark: assignments/lab5.md
    - Lab 6 - Python and Socket Basics: assignments/lab6.md
    - Proxy Labs: 
      - Proxy Project Overview: assignments/proxy-labs.md
      - Proxy Part 1 (Lab 7): assignments/lab7.md
      - Proxy Part 2 (Lab 8): assignments/lab8.md
    #  - Proxy Part 3 (Lab 9): assignments/lab9.md
  - Resources:
    - Concepts and Theory:
      - Domain Name System (DNS): notes/dns-overview.md
      - Routers: notes/router-overview.md
      - Ethernet Switches: notes/ethernet-switches.md
    - Guides:
      - Getting Pi Materials: resources/pi-materials.md
      - Digital Ocean Signup: resources/digital-ocean.md
      - Basic IP Address Planning: resources/address-planning.md
      - Introduction to Iptables: resources/iptables.md
      - Understanding Netfilter/Iptables Hooks: resources/netfilter-hooks.md
      - Linux Wireless Configuration: resources/wifi-reference.md
      - Zone File Reference: resources/zone-file-format.md
      - Special Network Interfaces (VLANs and Dummies): resources/vlans-and-dummies.md
      - Configuring Routing Links: resources/configure-routing-links.md
      - Install and Configure WireGuard: resources/setup-wireguard.md
      - Install Free Range Routing (FRR): resources/setup-frr.md
      - Using ssh-agent: resources/ssh-agent.md
    - Quick Reference:
      - Intro to Markdown: resources/markdown.md
      - Intro to Bash: resources/bash.md
      - Mac/Win/Linux Networking: resources/host-config.md
      - Install Wireshark: resources/wireshark-install.md
      - Install TShark: resources/tshark-install.md
      - Troubleshooting DHCP: resources/manage-dhcp.md
      - Managing DNS Clients: resources/dns-clients.md
  - Contact Us: contact.md

# Configuration
theme: yeti

# Extensions
markdown_extensions:
- admonition
- codehilite:
    guess_lang: false
- attr_list
- def_list
- footnotes
- meta
- sane_lists
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde

copyright: 'Copyright &copy; 2020 Clinton Campbell'
