# Project Information
site_name: INFO 314 Course Resources
site_description: Documentation and Resources for INFO 314
site_author: Clinton Campbell
site_url: https://info314.tcpip.dev

# Repository
repo_name: quirktree/info314-website
repo_url: https://github.com/quirktree/info314-website
edit_uri: ""

# Site Layout
nav:
  - Home: index.md
  - Projects:
    - 1 - Pi Setup:
      - Raspberry Pi Setup: assignments/pi-setup.md
      - Wireless Configuration Reference: resources/wifi-reference.md
      - UW Wireless Reference: resources/uw-wireless.md
      - networkd Setup: assignments/networkd-setup.md
    - 2 - Set up a DHCP Server:
      - IP Address Planning Reference: resources/address-planning.md
      - Installing and Configuring the ISC DHCP Server: assignments/dhcp-setup.md
    - 3 - Configure Routing and NAT:
      - Router Setup: assignments/router-setup.md
      - Introduction to nftables: resources/nftables.md
    - 4 - Configure a DNS Resolver:
      - DNS Resolver Setup: assignments/resolver-setup.md
    - Report - NAT and DNS Analysis:
      - Instructions: assignments/analysis-report.md
      - Installing TShark: resources/tshark-install.md
    - 5 - Configure an Authoritative Name Server:
      - Authoritative Zone Setup: assignments/dns-zone-setup.md
      - DNS Zone Reference: resources/zone-file-format.md
    - Extra Credit:
      - VLAN Challenge: / # assignments/vlan-challenge.md
    # - Final WAN Project:
    #   - Project Requirements: / # assignments/final-project.md
    #   - Resources:
    #     - PiCANN Registry: / # https://docs.google.com/spreadsheets/d/1A3uCrVmrwoPdA0LvMH6IyRkU1_BLXhbVRjIadtc__E0/edit?usp=sharing
    #     - Installing WireGuard: / # resources/setup-wireguard.md
    #     - Installing Free Range Routing: / # resources/setup-frr.md
    #     - WireGuard Configuration: / # resources/wireguard-configuration.md
    #     - Configure Routing Links: / # resources/configure-routing-links.md
    #     - Configure Dummy Interfaces: / # resources/dummy-interfaces.md
  - Labs:
    # - Lab 1 - Core Technical Skills: assignments/lab1.md
    - Lab 1 - Analyzing DHCP and ARP with Wireshark: assignments/wireshark01.md
    - Lab 2 - Analyze DNS & HTTP in Wireshark: assignments/wireshark02.md
    - Lab 3 - Analyze Zeroconf in Wireshark: assignments/wireshark03.md
    - Lab 4 - Analyze TCP with ncat and Wireshark: assignments/wireshark04.md
    # - Lab - Python and Socket Basics: / #assignments/lab6.md
    # - Proxy Project Overview: / #assignments/proxy-labs.md
    # - Lab - Proxy Part 1:  / #assignments/lab7.md
    # - Lab - Proxy Part 2: / #assignments/lab8.md
    # - Lab - Proxy Part 3: / #assignments/lab9.md
    # - Lab - Proxy Part 4: / #assignments/lab10.md
  - Resources:
    - Getting Started:
      - Intro to Markdown: resources/markdown.md
      - Intro to Bash: resources/bash.md
    - Concepts and Theory:
      - Basic IP Address Planning: resources/address-planning.md
      - Domain Name System (DNS): notes/dns-overview.md
      - DNS Zone Files: resources/zone-file-format.md
      - Ethernet Switches: notes/ethernet-switches.md
      - Routers: notes/router-overview.md
    - Core Settings and Tools:
      - Getting Started with SSH: resources/ssh-primer.md
      - Using the SSH Agent: resources/ssh-agent.md
      - Install Wireshark: resources/wireshark-install.md
      - Install TShark: resources/tshark-install.md
      - Mac/Win/Linux Networking: resources/host-config.md
      - Troubleshooting DHCP: resources/manage-dhcp.md
      - Managing DNS Clients: resources/dns-clients.md
    - General Linux Networking:
      - Firewalls:
        - Introduction to nftables: resources/nftables.md
        - Understanding netfilter Hooks: resources/netfilter-hooks.md
        - Introduction to iptables: resources/iptables.md
      - Network Interfaces:
        - Loopback Interfaces : resources/loopback-interfaces.md
        - Dummy Interfaces : resources/dummy-interfaces.md
        - VLAN Interfaces : resources/vlan-interfaces.md
      - Virtual Private Networking:
        - Install and Configure WireGuard: resources/setup-wireguard.md
      - Wireless:
        - wpa_supplicant Reference: resources/wifi-reference.md
    - Free Range Routing:
      - Install Free Range Routing (FRR): resources/setup-frr.md
      - Configuring Routing Links: resources/configure-routing-links.md
    - University of Washington Networks:
      - UW Wireless Network Reference: resources/uw-wireless.md

# Configuration
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    #- toc.integrate

  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

# Override some default css configs
extra_css:
    - stylesheets/extra.css

# Extensions
markdown_extensions:
- admonition
- attr_list
- def_list
- footnotes
- md_in_html
- meta
- sane_lists
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:materialx.emoji.to_svg
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tabbed:
    alternate_style: true 
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde
- pymdownx.emoji:
    emoji_index: !!python/name:materialx.emoji.twemoji
    emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: 'Copyright &copy; 2022 Clinton Campbell'
