# Project Information
site_name: INFO 314 Course Resources
site_description: Documentation and Resources for INFO 314
site_author: Clinton Campbell
site_url: https://info314.tcpip.dev

# Repository
repo_name: quirktree/info314-website
repo_url: https://github.com/quirktree/info314-website
edit_uri: ""

# Site Layout
nav:
  - Home: index.md
  - Projects:
    - 1 - Pi Setup:
      - Raspberry Pi Setup: assignments/pi-setup.md
      - networkd Setup: assignments/networkd-setup.md
      - Wifi Reference: resources/wifi-reference.md
    - 2 - Set up a DHCP Server:
      - IP Address Planning Reference: resources/address-planning.md
      - Installing and Configuring the ISC DHCP Server: assignments/dhcp-setup.md
  - Labs:
    - Lab 2: assignments/lab2.md
    - Lab 3: assignments/lab3.md
  - Reference:
    - Intro to Markdown: resources/markdown.md
    - Intro to Bash: resources/bash.md
    - Mac/Win/Linux Networking: resources/host-config.md
    - Install Wireshark: resources/wireshark-install.md
    - Linux Wireless Reference: resources/wifi-reference.md
    - Troubleshooting DHCP: resources/manage-dhcp.md
    - Managing DNS Clients: resources/dns-clients.md

        #      - Asking for help: contact.md
        #- Resources:
        #- Pi Materials: resources/pi-materials.md
        #- Asking for help: contact.md
        #- Assignments:
        #- Projects:
        #- Labs:

# Configuration
theme: yeti

# Extensions
markdown_extensions:
- admonition
- codehilite:
    guess_lang: false
- attr_list
- def_list
- footnotes
- meta
- sane_lists
- toc:
    permalink: true
- pymdownx.arithmatex
- pymdownx.betterem:
    smart_enable: all
- pymdownx.caret
- pymdownx.critic
- pymdownx.details
- pymdownx.emoji:
    emoji_generator: !!python/name:pymdownx.emoji.to_svg
- pymdownx.inlinehilite
- pymdownx.keys
- pymdownx.magiclink
- pymdownx.mark
- pymdownx.smartsymbols
- pymdownx.superfences
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tilde

copyright: 'Copyright &copy; 2020 Clinton Campbell'
